trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: |
      yarn install
      yarn build:pilot
      yarn export

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'out'
    ArtifactName: 'BlinkAdminPortalFrontend'
    publishLocation: 'Container'
